Test on each platform without building on each platform (#33)
* Initial windows arm64

* Run tests on all platforms

---------

Co-authored-by: Jack Boswell (boswelja) <boswelja@outlook.com>

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -29,7 +29,7 @@ jobs:
       - name: Static checks
         run: ./gradlew apiCheck spotlessCheck
 
-  zig:
+  jvm-test-binaries:
     runs-on: macos-latest
     steps:
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
@@ -43,30 +43,94 @@ jobs:
       - run: zig build -p src/jvmMain/resources/jni
         working-directory: zstd-kmp
 
+      - run: ./gradlew :zstd-kmp:installJvmTestDistribution
+
       - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # ratchet:actions/upload-artifact@v4
         with:
           name: jni-binaries
           path: zstd-kmp/src/jvmMain/resources/jni
           if-no-files-found: error
 
+      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # ratchet:actions/upload-artifact@v4
+        with:
+          name: zstd-kmp-jvm-tests
+          path: zstd-kmp/build/install/jvmTest
+          if-no-files-found: error
+
+  native-test-binaries:
+    runs-on: macos-latest
+    steps:
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
+        with:
+          submodules: true
+
+      - run: ./gradlew :zstd-kmp:linkNativeDebugTests
+
+      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # ratchet:actions/upload-artifact@v4
+        with:
+          name: zstd-kmp-native-tests
+          path: zstd-kmp/build/bin
+          if-no-files-found: error
+
   platform-test:
     needs:
-      - zig
+      - jvm-test-binaries
+      - native-test-binaries
     strategy:
       fail-fast: false
       matrix:
-        os: [ubuntu-latest]
-        native-test-tasks: ["linuxX64Test"]
-        include:
-          - os: macos-latest-large
-            native-test-tasks: "macosX64Test iosX64Test"
-          - os: macos-latest
-            native-test-tasks: "macosArm64Test iosSimulatorArm64Test"
-          - os: windows-latest
-            native-test-tasks: "mingwX64Test"
+        platform:
+          - os: macOS-13
+            native-target: macosX64
+          - os: macOS-15
+            native-target: macosArm64
+          - os: ubuntu-24.04
+            native-target: linuxX64
+          - os: ubuntu-24.04-arm
+            native-target: linuxArm64
+          - os: windows-2025
+            native-target: mingwX64
+          - os: windows-11-arm
+            native-target: skip
 
-    runs-on: ${{ matrix.os }}
+    runs-on: ${{ matrix.platform.os }}
 
+    steps:
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
+        with:
+          sparse-checkout: .github/workflows/.java-version
+          sparse-checkout-cone-mode: false
+
+      - uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # ratchet:actions/setup-java@v4
+        with:
+          distribution: 'zulu'
+          java-version-file: .github/workflows/.java-version
+
+      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # ratchet:actions/download-artifact@v4
+        with:
+          name: zstd-kmp-jvm-tests
+
+      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # ratchet:actions/download-artifact@v4
+        if: matrix.platform.native-target != 'skip'
+        with:
+          name: zstd-kmp-native-tests
+
+      - name: Run JVM tests
+        run: |
+          chmod +x bin/zstd-kmp-test
+          bin/zstd-kmp-test
+
+      - name: Run native tests
+        if: matrix.platform.native-target != 'skip'
+        shell: bash
+        run: |
+          chmod +x ${{ matrix.platform.native-target }}/debugTest/test.*
+          ${{ matrix.platform.native-target }}/debugTest/test.*
+
+  android-test:
+    runs-on: ubuntu-latest
+    needs:
+      - jvm-test-binaries
     steps:
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
         with:
@@ -77,26 +141,13 @@ jobs:
           distribution: 'zulu'
           java-version-file: .github/workflows/.java-version
 
-      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # ratchet:actions/download-artifact@v4
-        with:
-          name: jni-binaries
-          path: zstd-kmp/src/jvmMain/resources/jni
-
-      - name: Kotlin/JVM test
-        run: ./gradlew jvmTest
-
-      - name: Kotlin/Native test
-        run: ./gradlew ${{ matrix.native-test-tasks }}
-
       - name: Enable KVM (for Android test)
-        if: matrix.os == 'ubuntu-latest'
         run: |
           echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
           sudo udevadm control --reload-rules
           sudo udevadm trigger --name-match=kvm
 
       - name: Android test
-        if: matrix.os == 'ubuntu-latest'
         uses: reactivecircus/android-emulator-runner@1dcd0090116d15e7c562f8db72807de5e036a4ed # ratchet:reactivecircus/android-emulator-runner@v2
         with:
           api-level: 29
@@ -110,11 +161,25 @@ jobs:
           path: '**/build/reports/tests/**'
           retention-days: 1
 
-  publish:
+  final-status:
+    if: ${{ !cancelled() }}
+    runs-on: ubuntu-latest
     needs:
       - platform-test
+      - android-test
       - static-checks
-      - zig
+    steps:
+      - name: Check
+        run: |
+          results=$(tr -d '\n' <<< '${{ toJSON(needs.*.result) }}')
+          if ! grep -q -v -E '(failure|cancelled)' <<< "$results"; then
+            echo "One or more required jobs failed"
+            exit 1
+          fi
+
+  publish:
+    needs:
+      - final-status
     runs-on: ubuntu-latest
     if: ${{startsWith(github.ref, 'refs/tags/') && github.repository == 'square/zstd-kmp' }}
 
